# Generated by Django 6.0.2 on 2026-03-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CalculationInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bouwjaar", models.PositiveIntegerField()),
                ("bruto_vloeroppervlak", models.FloatField()),
                ("aantal_woningen", models.PositiveIntegerField()),
                ("mechanische_ventilatie_aanwezig", models.BooleanField()),
                ("vloerverwarming_aanwezig", models.BooleanField()),
                ("inpandige_berging_aanwezig", models.BooleanField()),
                ("ruimte_op_het_dak_aanwezig", models.BooleanField()),
                (
                    "type_dak",
                    models.CharField(
                        choices=[
                            ("plat_dak", "Plat dak"),
                            ("schuin_dak", "Schuin dak"),
                        ],
                        max_length=20,
                    ),
                ),
                ("tapwater_op_gas", models.BooleanField()),
                ("gasverbruik_per_woning", models.FloatField()),
                ("gasverbruik_vve_totaal", models.FloatField()),
                ("elektriciteitsverbruik_per_woning", models.FloatField()),
                ("elektriciteitsverbruik_vve_totaal", models.FloatField()),
                ("gecontracteerd_vermogen", models.FloatField()),
                (
                    "huidige_warmtesysteem",
                    models.CharField(
                        choices=[
                            ("warmtepomp", "Warmtepomp"),
                            ("cv_ketel", "Cv-ketel"),
                            ("anders", "Anders"),
                        ],
                        max_length=20,
                    ),
                ),
                ("volledig_gasloos", models.BooleanField()),
                ("wens_tot_koelen", models.BooleanField()),
            ],
            options={
                "verbose_name": "Calculation input",
                "verbose_name_plural": "Calculation inputs",
            },
        ),
    ]
