# Generated by Django 4.2.16 on 2026-03-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculation_inputs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naam", models.CharField(max_length=64, unique=True)),
                ("waarde", models.DecimalField(decimal_places=9, max_digits=18)),
            ],
            options={
                "verbose_name": "Conversie",
                "verbose_name_plural": "Conversies",
            },
        ),
    ]
