# Generated by Django 6.0.2 on 2026-03-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculation_inputs", "0002_conversie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calculationinput",
            name="bruto_vloeroppervlak",
            field=models.DecimalField(decimal_places=9, max_digits=18),
        ),
        migrations.AlterField(
            model_name="calculationinput",
            name="elektriciteitsverbruik_per_woning",
            field=models.DecimalField(decimal_places=9, max_digits=18),
        ),
        migrations.AlterField(
            model_name="calculationinput",
            name="elektriciteitsverbruik_vve_totaal",
            field=models.DecimalField(decimal_places=9, max_digits=18),
        ),
        migrations.AlterField(
            model_name="calculationinput",
            name="gasverbruik_per_woning",
            field=models.DecimalField(decimal_places=9, max_digits=18),
        ),
        migrations.AlterField(
            model_name="calculationinput",
            name="gasverbruik_vve_totaal",
            field=models.DecimalField(decimal_places=9, max_digits=18),
        ),
        migrations.AlterField(
            model_name="calculationinput",
            name="gecontracteerd_vermogen",
            field=models.DecimalField(decimal_places=9, max_digits=18),
        ),
    ]
