# Generated by Django 4.2.16 on 2026-03-30 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "calculation_inputs",
            "0003_alter_calculationinput_bruto_vloeroppervlak_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="calculationinput",
            name="koken_op_gas",
            field=models.BooleanField(default=False),
        ),
    ]
