# Generated by Django 4.2.16 on 2026-04-01 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculation_inputs", "0004_calculationinput_koken_op_gas"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalculationDashboard",
            fields=[],
            options={
                "verbose_name": "Berekeningen",
                "verbose_name_plural": "Berekeningen",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("calculation_inputs.calculationinput",),
        ),
    ]
