# Generated by Django 4.2.16 on 2026-04-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculation_inputs", "0005_calculationdashboard"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnergyPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naam", models.CharField(max_length=64, unique=True)),
                (
                    "prijs_eur_per_gj",
                    models.DecimalField(
                        blank=True,
                        decimal_places=9,
                        max_digits=18,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Energy price",
                "verbose_name_plural": "Energy prices",
            },
        ),
    ]
