# Generated by Django 4.2.16 on 2026-04-07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculation_inputs", "0006_energyprice"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(
                    name="CalculationDashboard",
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="CalculationInput",
            new_name="GebruikersInvoer",
        ),
        migrations.RenameModel(
            old_name="EnergyPrice",
            new_name="EnergiePrijs",
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="CalculationDashboard",
                    fields=[],
                    options={
                        "verbose_name": "Berekeningen",
                        "verbose_name_plural": "Berekeningen",
                        "proxy": True,
                        "indexes": [],
                        "constraints": [],
                    },
                    bases=("calculation_inputs.gebruikersinvoer",),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="gebruikersinvoer",
            options={
                "verbose_name": "Gebruikersinvoer",
                "verbose_name_plural": "Gebruikersinvoer",
            },
        ),
        migrations.AlterModelOptions(
            name="energieprijs",
            options={
                "verbose_name": "Energieprijs",
                "verbose_name_plural": "Energieprijzen",
            },
        ),
    ]
