# Generated by Django 4.2.16 on 2026-04-13 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculation_inputs", "0007_rename_models_to_dutch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gebruikersinvoer",
            name="gasverbruik_per_woning",
        ),
    ]
