# Generated by Django 4.2.16 on 2026-04-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculation_inputs", "0008_remove_gebruikersinvoer_gasverbruik_per_woning"),
    ]

    operations = [
        migrations.AddField(
            model_name="gebruikersinvoer",
            name="dubbel_glas",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gebruikersinvoer",
            name="wtw_aanwezig",
            field=models.BooleanField(default=False),
        ),
    ]
