# Generated by Django 4.2.16 on 2026-04-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculation_inputs", "0009_gebruikersinvoer_dubbel_glas_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gebruikersinvoer",
            name="buurtcode",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="gebruikersinvoer",
            name="jaar_vervangen",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
