# Generated by Django 6.0.2 on 2026-04-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculation_inputs", "0010_gebruikersinvoer_buurtcode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gebruikersinvoer",
            name="beschikbare_collectieve_ruimte_binnen_m2",
            field=models.DecimalField(decimal_places=9, default=20, max_digits=18),
        ),
        migrations.AddField(
            model_name="gebruikersinvoer",
            name="beschikbare_collectieve_ruimte_buiten_m2",
            field=models.DecimalField(decimal_places=9, default=100, max_digits=18),
        ),
        migrations.AddField(
            model_name="gebruikersinvoer",
            name="beschikbare_ruimte_in_woning_m2",
            field=models.DecimalField(decimal_places=9, default=1, max_digits=18),
        ),
    ]
