# Generated by Django 6.0.4 on 2026-05-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "calculation_inputs",
            "0011_gebruikersinvoer_beschikbare_collectieve_ruimte_binnen_m2_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="gebruikersinvoer",
            name="huidig_systeem",
            field=models.CharField(
                choices=[("collectief", "Collectief"), ("individueel", "Individueel")],
                default="collectief",
                max_length=20,
            ),
        ),
    ]
