# Generated by Django 6.0.4 on 2026-05-13 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calculation_inputs", "0012_gebruikersinvoer_huidig_systeem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gebruikersinvoer",
            name="elektriciteitsverbruik_per_woning",
        ),
        migrations.RemoveField(
            model_name="gebruikersinvoer",
            name="elektriciteitsverbruik_vve_totaal",
        ),
        migrations.RemoveField(
            model_name="gebruikersinvoer",
            name="gecontracteerd_vermogen",
        ),
        migrations.RemoveField(
            model_name="gebruikersinvoer",
            name="huidige_warmtesysteem",
        ),
        migrations.RemoveField(
            model_name="gebruikersinvoer",
            name="inpandige_berging_aanwezig",
        ),
        migrations.RemoveField(
            model_name="gebruikersinvoer",
            name="ruimte_op_het_dak_aanwezig",
        ),
        migrations.RemoveField(
            model_name="gebruikersinvoer",
            name="type_dak",
        ),
        migrations.RemoveField(
            model_name="gebruikersinvoer",
            name="volledig_gasloos",
        ),
    ]
