# Generated by Django 4.2.16 on 2026-03-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subsysteem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naam", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("kengetal", "Kengetal"),
                            ("stadswarmte", "Stadswarmte"),
                        ],
                        default="kengetal",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Subsysteem",
                "verbose_name_plural": "Subsystemen",
            },
        ),
        migrations.CreateModel(
            name="Hoofdsysteem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naam", models.CharField(max_length=255)),
                ("beschrijving", models.TextField(blank=True, null=True)),
                ("beschrijving_url", models.URLField(blank=True, null=True)),
                (
                    "subsystemen",
                    models.ManyToManyField(
                        related_name="hoofdsystemen", to="systemen.subsysteem"
                    ),
                ),
            ],
            options={
                "verbose_name": "Hoofdsysteem",
                "verbose_name_plural": "Hoofdsystemen",
            },
        ),
    ]
