# Generated by Django 4.2.16 on 2026-03-25 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("systemen", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subsysteem",
            name="calculation_method",
            field=models.CharField(
                choices=[("Investering", "Investering")],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
    ]
