# Generated by Django 4.2.16 on 2026-04-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("systemen", "0002_add_subsysteem_calculation_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subsysteem",
            name="calculation_method",
            field=models.CharField(
                choices=[("Investering", "Investering"), ("openbron", "Openbron")],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
    ]
