# Generated by Django 6.0.2 on 2026-05-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("systemen", "0007_alter_subsysteem_calculation_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="hoofdsysteem",
            name="beschrijving_url_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
