# Generated by Django 4.2.16 on 2026-03-18 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("systemen", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subkengetal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scenario",
                    models.CharField(
                        choices=[
                            ("laag", "Laag"),
                            ("midden", "Midden"),
                            ("hoog", "Hoog"),
                        ],
                        max_length=10,
                    ),
                ),
                ("investeringskosten", models.FloatField()),
                ("levensduur", models.IntegerField()),
                ("beheer_en_onderhoud", models.FloatField()),
                ("verhouding_vermogen_bron", models.FloatField(blank=True, null=True)),
                ("debiet_bron", models.IntegerField(blank=True, null=True)),
                ("energie_bron", models.FloatField(blank=True, null=True)),
                (
                    "delta_temperatuur_retour",
                    models.IntegerField(blank=True, null=True),
                ),
                ("onttrekkingsvermogen", models.FloatField(blank=True, null=True)),
                (
                    "subsysteem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subkengetallen",
                        to="systemen.subsysteem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subkengetal",
                "verbose_name_plural": "Subkengetallen",
            },
        ),
        migrations.CreateModel(
            name="Hoofdkengetal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scenario",
                    models.CharField(
                        choices=[
                            ("laag", "Laag"),
                            ("midden", "Midden"),
                            ("hoog", "Hoog"),
                        ],
                        max_length=10,
                    ),
                ),
                ("cop_tap", models.FloatField()),
                ("cop_cv", models.FloatField()),
                ("cop_gkw", models.FloatField()),
                (
                    "hoofdsysteem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hoofdkengetallen",
                        to="systemen.hoofdsysteem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hoofdkengetal",
                "verbose_name_plural": "Hoofdkengetallen",
            },
        ),
        migrations.AddConstraint(
            model_name="subkengetal",
            constraint=models.UniqueConstraint(
                fields=("scenario", "subsysteem"), name="uniek_scenario_subsysteem"
            ),
        ),
        migrations.AddConstraint(
            model_name="hoofdkengetal",
            constraint=models.UniqueConstraint(
                fields=("scenario", "hoofdsysteem"), name="uniek_scenario_hoofdsysteem"
            ),
        ),
    ]
