# Generated by Django 4.2.16 on 2026-03-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kengetallen", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlgemeenKengetal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scenario",
                    models.CharField(
                        choices=[
                            ("laag", "Laag"),
                            ("midden", "Midden"),
                            ("hoog", "Hoog"),
                        ],
                        max_length=10,
                    ),
                ),
                ("naam", models.CharField(max_length=255)),
                ("omschrijving", models.CharField(max_length=255)),
                ("waarde", models.FloatField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("tap", "TAP"),
                            ("cv", "CV"),
                            ("gkw", "GKW"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
