# Generated by Django 4.2.16 on 2026-03-25 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kengetallen", "0002_algemeenkengetal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="algemeenkengetal",
            name="type",
        ),
    ]
