# Generated by Django 6.0.2 on 2026-03-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kengetallen", "0003_remove_algemeenkengetal_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="algemeenkengetal",
            name="waarde",
            field=models.DecimalField(decimal_places=9, max_digits=18),
        ),
        migrations.AlterField(
            model_name="hoofdkengetal",
            name="cop_cv",
            field=models.DecimalField(decimal_places=9, max_digits=18),
        ),
        migrations.AlterField(
            model_name="hoofdkengetal",
            name="cop_gkw",
            field=models.DecimalField(decimal_places=9, max_digits=18),
        ),
        migrations.AlterField(
            model_name="hoofdkengetal",
            name="cop_tap",
            field=models.DecimalField(decimal_places=9, max_digits=18),
        ),
        migrations.AlterField(
            model_name="subkengetal",
            name="beheer_en_onderhoud",
            field=models.DecimalField(decimal_places=9, max_digits=18),
        ),
        migrations.AlterField(
            model_name="subkengetal",
            name="energie_bron",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="subkengetal",
            name="investeringskosten",
            field=models.DecimalField(decimal_places=9, max_digits=18),
        ),
        migrations.AlterField(
            model_name="subkengetal",
            name="onttrekkingsvermogen",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=18, null=True
            ),
        ),
        migrations.AlterField(
            model_name="subkengetal",
            name="verhouding_vermogen_bron",
            field=models.DecimalField(
                blank=True, decimal_places=9, max_digits=18, null=True
            ),
        ),
    ]
