# Generated by Django 4.2.16 on 2026-03-25 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kengetallen", "0004_alter_algemeenkengetal_waarde_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="algemeenkengetal",
            options={
                "verbose_name": "Algemeen kengetal",
                "verbose_name_plural": "Algemene kengetallen",
            },
        ),
    ]
