# Generated by Django 4.2.16 on 2026-04-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kengetallen", "0005_alter_algemeenkengetal_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="StadsverwarmingKengetal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "klanttype",
                    models.CharField(
                        choices=[
                            ("particulier", "Particulier"),
                            ("zakelijk", "Zakelijk"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "producttype",
                    models.CharField(
                        choices=[
                            ("warmte", "Warmte"),
                            ("koude", "Koude"),
                            ("warmte_koude", "Warmte + koude"),
                        ],
                        max_length=20,
                    ),
                ),
                ("kostetype", models.CharField(max_length=255)),
                (
                    "eenheid",
                    models.CharField(
                        choices=[
                            ("vast", "Vast"),
                            ("variabel", "Variabel"),
                            ("geclassificeerd", "Geclassificeerd"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("eenmalig", "Eenmalig"),
                            ("jaarlijks", "Jaarlijks"),
                            ("maandelijks", "Maandelijks"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "vermogen_berekenen_op",
                    models.CharField(
                        blank=True,
                        choices=[("warmte", "Warmte"), ("koude", "Koude")],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "kw_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=9,
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "kw_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=9,
                        max_digits=18,
                        null=True,
                    ),
                ),
                (
                    "waarde_1",
                    models.DecimalField(decimal_places=9, max_digits=18),
                ),
                (
                    "waarde_2",
                    models.DecimalField(decimal_places=9, max_digits=18),
                ),
            ],
            options={
                "verbose_name": "Stadsverwarming kengetal",
                "verbose_name_plural": "Stadsverwarming kengetallen",
            },
        ),
        migrations.AddIndex(
            model_name="stadsverwarmingkengetal",
            index=models.Index(
                fields=["klanttype", "producttype"],
                name="kengetallen_klantty_0f0122_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stadsverwarmingkengetal",
            index=models.Index(
                fields=["kostetype"], name="kengetallen_kostety_4b1d7b_idx"
            ),
        ),
    ]
