# Generated by Django 4.2.16 on 2026-04-08 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kengetallen", "0006_stadsverwarmingkengetal"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="stadsverwarmingkengetal",
            new_name="kengetallen_klantty_21f4ce_idx",
            old_name="kengetallen_klantty_0f0122_idx",
        ),
        migrations.RenameIndex(
            model_name="stadsverwarmingkengetal",
            new_name="kengetallen_kostety_9996df_idx",
            old_name="kengetallen_kostety_4b1d7b_idx",
        ),
    ]
