# Generated by Django 4.2.16 on 2026-04-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kengetallen", "0007_gelijktijdigheidcv"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectieveWarmtepompKengetal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naam", models.CharField(max_length=64, unique=True)),
                (
                    "omschrijving",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "waarde",
                    models.DecimalField(decimal_places=9, default=0, max_digits=18),
                ),
            ],
            options={
                "verbose_name": "Collectieve warmtepomp formule",
                "verbose_name_plural": "Collectieve warmtepomp formule kengetallen",
            },
        ),
    ]
