# Generated by Django 6.0.2 on 2026-04-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kengetallen", "0008_collectievewarmtepompkengetal"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collectievewarmtepompkengetal",
            options={
                "verbose_name": "Collectieve warmtepomp kengetal",
                "verbose_name_plural": "Collectieve warmtepomp kengetallen",
            },
        ),
        migrations.AddField(
            model_name="subkengetal",
            name="staffel",
            field=models.DecimalField(
                blank=True, decimal_places=9, default=None, max_digits=18, null=True
            ),
        ),
    ]
