# Generated by Django 4.2.16 on 2026-04-23 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kengetallen", "0009_alter_collectievewarmtepompkengetal_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Warmteprogramma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("warmtenet_start", models.IntegerField(blank=True, null=True)),
                ("warmtenet_stop", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Warmteprogramma kengetal",
                "verbose_name_plural": "Warmteprogramma kengetallen",
                "indexes": [
                    models.Index(
                        fields=["categorie"], name="kengetallen_categor_9c5353_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BuurtcodeWarmteprogramma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("buurtcode", models.CharField(max_length=16, unique=True)),
                (
                    "warmteprogramma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="buurtcodes",
                        to="kengetallen.warmteprogramma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buurtcode warmteprogramma",
                "verbose_name_plural": "Buurtcode warmteprogramma",
                "indexes": [
                    models.Index(
                        fields=["buurtcode"], name="kengetallen_buurtco_4e809f_idx"
                    )
                ],
            },
        ),
    ]
