# Generated by Django 6.0.4 on 2026-04-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kengetallen", "0012_collectieveruimtebuiten"),
    ]

    operations = [
        migrations.CreateModel(
            name="EliminatieKengetal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naam", models.CharField(max_length=255, unique=True)),
                ("woningen_min", models.IntegerField()),
                ("woningen_max", models.IntegerField(blank=True, null=True)),
                (
                    "benodigde_ruimte_in_woning_m2",
                    models.DecimalField(decimal_places=9, max_digits=18),
                ),
                ("stadsverwarming_nodig", models.BooleanField(default=False)),
                ("mechanische_ventilatie_nodig", models.BooleanField(default=False)),
                ("kan_koelen", models.BooleanField(default=False)),
                ("laag_energieverbruik", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Eliminatie kengetal",
                "verbose_name_plural": "Eliminatie kengetallen",
                "ordering": ["naam", "woningen_min"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("woningen_max__isnull", True),
                            ("woningen_max__gte", models.F("woningen_min")),
                            _connector="OR",
                        ),
                        name="eliminatiekengetal_woningen_max_gte_min_or_null",
                    )
                ],
            },
        ),
    ]
