# Generated by Django 6.0.4 on 2026-05-08 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kengetallen", "0013_eliminatiekengetal"),
        ("systemen", "0007_alter_subsysteem_calculation_method"),
    ]

    operations = [
        migrations.CreateModel(
            name="MultiCriteriaAnalyseKengetal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "huidig_systeem_collectief",
                    models.DecimalField(decimal_places=9, max_digits=18),
                ),
                (
                    "huidig_systeem_individueel",
                    models.DecimalField(decimal_places=9, max_digits=18),
                ),
                (
                    "vloerverwarming_aanwezig_waar",
                    models.DecimalField(decimal_places=9, max_digits=18),
                ),
                (
                    "vloerverwarming_aanwezig_onwaar",
                    models.DecimalField(decimal_places=9, max_digits=18),
                ),
                (
                    "hoofdsysteem",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mca_kengetal",
                        to="systemen.hoofdsysteem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Multi-criteria analyse kengetal",
                "verbose_name_plural": "Multi-criteria analyse kengetallen",
                "ordering": ["hoofdsysteem"],
            },
        ),
    ]
