# Generated by Django 6.0.4 on 2026-05-08 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kengetallen", "0014_multicriteriaanalysekengetal"),
    ]

    operations = [
        migrations.CreateModel(
            name="McdaHoofdcriterium",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naam", models.CharField(max_length=255, unique=True)),
                ("wegingsfactor", models.DecimalField(decimal_places=9, max_digits=18)),
            ],
            options={
                "verbose_name": "MCDA hoofdcriterium",
                "verbose_name_plural": "MCDA hoofdcriteria",
                "ordering": ["naam"],
            },
        ),
        migrations.CreateModel(
            name="McdaSubcriterium",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("naam", models.CharField(max_length=255)),
                (
                    "relatieve_wegingsfactor",
                    models.DecimalField(decimal_places=9, max_digits=18),
                ),
                (
                    "hoofdcriterium",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcriteria",
                        to="kengetallen.mcdahoofdcriterium",
                    ),
                ),
            ],
            options={
                "verbose_name": "MCDA subcriterium",
                "verbose_name_plural": "MCDA subcriteria",
                "ordering": ["hoofdcriterium", "naam"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("hoofdcriterium", "naam"),
                        name="uniek_mcda_hoofcriterium_naam",
                    )
                ],
            },
        ),
    ]
