# Generated by Django 6.0.2 on 2026-05-21 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kengetallen", "0015_mcdahoofdcriterium_mcdasubcriterium"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stadsverwarmingkengetal",
            old_name="waarde_2",
            new_name="negatieve_factor",
        ),
        migrations.RenameField(
            model_name="stadsverwarmingkengetal",
            old_name="waarde_1",
            new_name="positieve_factor",
        ),
    ]
