# Generated by Django 6.0.4 on 2026-06-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "kengetallen",
            "0016_rename_waarde_2_stadsverwarmingkengetal_negatieve_factor_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="GasverbruikGegeven",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("postcode_start", models.CharField(max_length=7)),
                ("postcode_eind", models.CharField(max_length=7)),
                (
                    "gemiddeld_verbruik",
                    models.DecimalField(decimal_places=9, max_digits=18),
                ),
            ],
            options={
                "verbose_name": "Gasverbruikgegeven",
                "verbose_name_plural": "Gasverbruikgegevens",
                "ordering": ["postcode_start", "postcode_eind"],
                "indexes": [
                    models.Index(
                        fields=["postcode_start"], name="kengetallen_postcod_872f7f_idx"
                    ),
                    models.Index(
                        fields=["postcode_eind"], name="kengetallen_postcod_314166_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("postcode_start", "postcode_eind"),
                        name="uniek_postcode_start_postcode_eind_gasverbruik",
                    )
                ],
            },
        ),
    ]
