# Generated by Django 6.0.4 on 2026-07-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("systemen", "0008_hoofdsysteem_beschrijving_url_title"),
        ("kengetallen", "0017_gasverbruikgegeven"),
    ]

    operations = [
        migrations.AddField(
            model_name="warmteprogramma",
            name="hoofdsystemen",
            field=models.ManyToManyField(
                blank=True,
                related_name="warmteprogrammas",
                to="systemen.hoofdsysteem",
            ),
        ),
    ]
