# Generated by Django 6.0.4 on 2026-07-13 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kengetallen", "0018_warmteprogramma_hoofdsystemen"),
        ("systemen", "0008_hoofdsysteem_beschrijving_url_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectieveRuimteTuin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("n_min", models.IntegerField()),
                ("n_max", models.IntegerField(blank=True, null=True)),
                ("vereiste_m2", models.DecimalField(decimal_places=9, max_digits=18)),
                (
                    "hoofdsysteem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collectieve_ruimte_tuin",
                        to="systemen.hoofdsysteem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Collectieve ruimte tuin",
                "verbose_name_plural": "Collectieve ruimte tuin",
                "ordering": ["hoofdsysteem", "n_min"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("hoofdsysteem", "n_min", "n_max"),
                        name="uniek_hoofdsysteem_n_min_n_max_collectieve_ruimte_tuin",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("n_max__isnull", True),
                            ("n_max__gte", models.F("n_min")),
                            _connector="OR",
                        ),
                        name="collectieve_ruimte_tuin_n_max_gte_n_min_or_null",
                    ),
                ],
            },
        ),
    ]
